name: release

on:
  - repository_dispatch

jobs:
  release-fms-file-explorer-electron:
    if: github.event.action == 'on-demand-release'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@master
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@master
        with:
          node-version: 12

      - name: Use npm@7
        run: npm install --global npm@next-7

      - name: Build/release Electron app
        uses: GabeMedrash/action-electron-builder@fms-file-explorer
        env:
          # Used to code sign artifacts produced for Windows
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        with:
          # N.b.: mac.identity is explicitly set to null to short-circuit attempt
          # at code signing macOS artifact. Remove when/if attempting to accomplish that.
          config_overrides: >
            {
              "extraMetadata": {
                "version": "${{ github.event.client_payload.version }}"
              },
              "mac": {
                "identity": null
              }
            }

          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          package_root: "packages/fms-file-explorer-electron"

          # Always release when repo dispatch event is of type "release"
          release: true
