name: release

on:
  push:
    tags:
      # Match any tags that start with 'v'
      - v*

jobs:
  release-fms-file-explorer-desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@main
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@main
        with:
          node-version: 16

      - name: Install deps and build app
        env:
          AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
        run: |
          npm ci
          npm run --prefix packages/desktop build

      - name: Build artifact and release Mac
        if: matrix.os == 'macos-latest'
        working-directory: packages/desktop
        run: npx --no-install electron-builder --mac --publish always
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build artifact and release Linux
        if: matrix.os == 'ubuntu-latest'
        working-directory: packages/desktop
        run: npx --no-install electron-builder --linux --publish always
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build artifact and release Windows
        if: matrix.os == 'windows-latest'
        working-directory: packages/desktop
        run: npx --no-install electron-builder --windows --publish always
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # Windows certs
          CSC_LINK: ${{secrets.CSC_LINK}}
          CSC_KEY_PASSWORD: ${{secrets.CSC_KEY_PASSWORD}}
